apiVersion: v1

kind: Pod

metadata: 
  name: podby01
  namespace: 01112024ns

spec:
  containers:
    - name: nginxcontainer
      image: nginx:latest
      ports:
        - containerPort: 80

      volumeMounts:
        - mountPath: /var/logs
          name: mystoragemount

  volumes:
    - name: mystoragemount
      persistentVolumeClaim: 
        claimName: mypvc