apiVersion: v1

kind: PersistentVolume

metadata:
  name: mypv01
  

spec:
  accessModes:
    - ReadWriteMany

  azureFile:
    secretName: azure-secret
    shareName: abfileshare
  
  capacity:
    storage: 10Gi


  storageClassName: default

  persistentVolumeReclaimPolicy: Delete  # or Retain
