apiVersion: v1

kind: Pod

metadata: 
  name: podwithpv
  namespace: abhi-ns

spec: 
  containers:
    - name: nginx
      image: nginx:latest

      ports:
        - containerPort: 80

      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginxdata

  volumes:
    - name: nginxdata
      persistentVolumeClaim:
        claimName: mypvc
