apiVersion: v1

kind: PersistentVolume

metadata:
  name: mypv
  

spec:
  accessModes:
  - ReadWriteMany

  azureFile:
    secretName: azure-secret
    shareName: abfileshare
    secretNamespace: abhi-ns

  storageClassName: default

  capacity:
    storage: 50Gi
  