apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: abhi-ns

spec:
  accessModes:
  - ReadWriteMany

  storageClassName: default

  resources:
    requests:
      storage: 10Gi