apiVersion: v1

kind: PersistentVolume

metadata:
  name: satpv

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: sat

  capacity:
    storage: 10Gi

  azureFile:
    secretName: azure-secret-29
    shareName: sat-share

  persistentVolumeReclaimPolicy: Retain