apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: pvcwith-sc
  namespace: sat-ns

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: sat-sc

  resources:
    requests: 
      storage: 20Gi
